### ISSUE TITLE
Nginx Proxy Manager API tokens

### ISSUE THREAD

**Issue by BackspaceM** [benphelps/homepage-docs#150]
After building according to the wiki, modify services.yaml, where Nginx Proxy Manager returns an error:
API error: Unknown error
URL: http://192.168.X.X:81/api/tokens
Original error:
{
     "errno": -110,
     "code": "ETIMEDOUT",
     "syscall": "connect",
     "address": "192.168.X.X",
     "port": 81
}
After the test on the webpage, you can get relevant information by deleting tokens. What should I do now to get the relevant API in the homepage

**Comment by BackspaceM** [comment]
My English is poor, please forgive me

**Comment by shamoon** [comment]
Start with https://gethomepage.dev/en/more/troubleshooting/

also you can ask in [discussions](https://github.com/benphelps/homepage/discussions)
