### ISSUE TITLE
Incomplete Search Results

### ISSUE THREAD

**Issue by MountainGod2** [benphelps/homepage-docs#63]
A couple of days ago someone in the Discord server mentioned that the search bar wasn't returning results for certain items. Figured I'd raise an issue here as I get the same behavior but don't know enough about how the search is indexed to try and debug
https://discord.com/channels/1019316731635834932/1019316732797653086/1088792234675150899

A few that I found in addition to the Nextcloud one they brought up were:
`Grafana`
`Prometheus`
`Pterodactyl`

but I didn't do a very comprehensive check.

![image](https://user-images.githubusercontent.com/88257202/227787796-d64ad88c-68ca-466c-af30-4d4ce1eac6eb.png)

**Comment by shamoon** [comment]
@benphelps anything on the search config side that might explain this?

**Comment by qudiqudi** [comment]
It looks like the Algolia crawler refuses it's job. Maybe an expired api key or subscription of some sort...

**Comment by benphelps** [comment]
There was a block in place because of a 20% difference in generated results.  This should be fixed now. 👍🏻 

<img width="629" alt="Screenshot 2023-04-01 at 3 07 32 PM" src="https://user-images.githubusercontent.com/82196/229287716-f335a23d-8434-4bf7-ac6e-b61a651b7eaa.png">
