### ISSUE TITLE
Proxmox widget showing no information

### ISSUE THREAD

**Issue by soupdiver** [benphelps/homepage-docs#94]
I created user/group/api token according to the docs and put into my `services.yaml`

```
    - Proxmox - Home:
        href: https://xxx:8006
        icon: proxmox.png
        widget:
          type: proxmox
          url: https://10.0.0.2:8006
          username: homepage@pam!hp
          password: xxx
```
I don't see any error or information in the ui/logs.

![image](https://github.com/benphelps/homepage-docs/assets/800562/463b2903-0187-488d-befc-7e14cae8b317)

![image](https://github.com/benphelps/homepage-docs/assets/800562/8e5db4d4-b138-47ac-83cf-0fdc650c9f3b)

```json
{"data":[{"id":"node/pve","level":"","node":"pve","cgroup-mode":2,"type":"node","status":"online"}]}
```

One thing I wonder:
When clicking the Permissions button in Proxmox for the API key it shows nothing. Could that be the issue? I thought it would have the same permissions as the user

![image](https://github.com/benphelps/homepage-docs/assets/800562/1eb5e439-07e2-4988-9f9b-16d0b93b7be6)

Running latest version of homepage.
Happy to provide more info if requried.

**Comment by shamoon** [comment]
Have a look at https://github.com/benphelps/homepage-docs/pull/82

In general, maintaining docs for these is annoying because the 'definitive' answer seems elusive...
